// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contributions.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countContributionsByUser = `-- name: CountContributionsByUser :one
SELECT COUNT(*) FROM contributions WHERE user_id = $1
`

func (q *Queries) CountContributionsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countContributionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContribution = `-- name: CreateContribution :one
INSERT INTO contributions (user_id, pool_id, amount, currency, stripe_pi_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, pool_id, amount, currency, status, payment_ref, stripe_pi_id, created_at, updated_at
`

type CreateContributionParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PoolID     uuid.UUID `json:"pool_id"`
	Amount     float64   `json:"amount"`
	Currency   string    `json:"currency"`
	StripePiID *string   `json:"stripe_pi_id"`
}

func (q *Queries) CreateContribution(ctx context.Context, arg CreateContributionParams) (Contribution, error) {
	row := q.db.QueryRow(ctx, createContribution,
		arg.UserID,
		arg.PoolID,
		arg.Amount,
		arg.Currency,
		arg.StripePiID,
	)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PoolID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentRef,
		&i.StripePiID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionByID = `-- name: GetContributionByID :one
SELECT id, user_id, pool_id, amount, currency, status, payment_ref, stripe_pi_id, created_at, updated_at FROM contributions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetContributionByID(ctx context.Context, id uuid.UUID) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContributionByID, id)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PoolID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentRef,
		&i.StripePiID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContributionByStripePI = `-- name: GetContributionByStripePI :one
SELECT id, user_id, pool_id, amount, currency, status, payment_ref, stripe_pi_id, created_at, updated_at FROM contributions WHERE stripe_pi_id = $1 LIMIT 1
`

func (q *Queries) GetContributionByStripePI(ctx context.Context, stripePiID *string) (Contribution, error) {
	row := q.db.QueryRow(ctx, getContributionByStripePI, stripePiID)
	var i Contribution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PoolID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentRef,
		&i.StripePiID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContributionsByUser = `-- name: ListContributionsByUser :many
SELECT id, user_id, pool_id, amount, currency, status, payment_ref, stripe_pi_id, created_at, updated_at FROM contributions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListContributionsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListContributionsByUser(ctx context.Context, arg ListContributionsByUserParams) ([]Contribution, error) {
	rows, err := q.db.Query(ctx, listContributionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Contribution{}
	for rows.Next() {
		var i Contribution
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PoolID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentRef,
			&i.StripePiID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumCompletedContributionsByUser = `-- name: SumCompletedContributionsByUser :one
SELECT COALESCE(SUM(amount), 0)::float8
FROM contributions
WHERE user_id = $1 AND status = 'completed'
`

func (q *Queries) SumCompletedContributionsByUser(ctx context.Context, userID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, sumCompletedContributionsByUser, userID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateContributionStatus = `-- name: UpdateContributionStatus :exec
UPDATE contributions
SET
    status      = $2,
    payment_ref = $3,
    updated_at  = NOW()
WHERE id = $1
`

type UpdateContributionStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	PaymentRef *string   `json:"payment_ref"`
}

func (q *Queries) UpdateContributionStatus(ctx context.Context, arg UpdateContributionStatusParams) error {
	_, err := q.db.Exec(ctx, updateContributionStatus, arg.ID, arg.Status, arg.PaymentRef)
	return err
}
