// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deliveries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDelivery = `-- name: CreateDelivery :one
INSERT INTO deliveries (fulfillment_id, tracking_number, carrier)
VALUES ($1, $2, $3)
RETURNING id, fulfillment_id, tracking_number, carrier, proof_photo_url, status, delivered_at, verified_at, verified_by, created_at, updated_at
`

type CreateDeliveryParams struct {
	FulfillmentID  uuid.UUID `json:"fulfillment_id"`
	TrackingNumber *string   `json:"tracking_number"`
	Carrier        *string   `json:"carrier"`
}

func (q *Queries) CreateDelivery(ctx context.Context, arg CreateDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, createDelivery, arg.FulfillmentID, arg.TrackingNumber, arg.Carrier)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.FulfillmentID,
		&i.TrackingNumber,
		&i.Carrier,
		&i.ProofPhotoUrl,
		&i.Status,
		&i.DeliveredAt,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryByFulfillmentID = `-- name: GetDeliveryByFulfillmentID :one
SELECT id, fulfillment_id, tracking_number, carrier, proof_photo_url, status, delivered_at, verified_at, verified_by, created_at, updated_at FROM deliveries WHERE fulfillment_id = $1 LIMIT 1
`

func (q *Queries) GetDeliveryByFulfillmentID(ctx context.Context, fulfillmentID uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByFulfillmentID, fulfillmentID)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.FulfillmentID,
		&i.TrackingNumber,
		&i.Carrier,
		&i.ProofPhotoUrl,
		&i.Status,
		&i.DeliveredAt,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeliveryByID = `-- name: GetDeliveryByID :one
SELECT id, fulfillment_id, tracking_number, carrier, proof_photo_url, status, delivered_at, verified_at, verified_by, created_at, updated_at FROM deliveries WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeliveryByID(ctx context.Context, id uuid.UUID) (Delivery, error) {
	row := q.db.QueryRow(ctx, getDeliveryByID, id)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.FulfillmentID,
		&i.TrackingNumber,
		&i.Carrier,
		&i.ProofPhotoUrl,
		&i.Status,
		&i.DeliveredAt,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeliveryStatus = `-- name: UpdateDeliveryStatus :exec
UPDATE deliveries
SET status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateDeliveryStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateDeliveryStatus(ctx context.Context, arg UpdateDeliveryStatusParams) error {
	_, err := q.db.Exec(ctx, updateDeliveryStatus, arg.ID, arg.Status)
	return err
}

const verifyDelivery = `-- name: VerifyDelivery :one
UPDATE deliveries
SET
    proof_photo_url = $2,
    status          = 'delivered',
    delivered_at    = $3,
    verified_at     = NOW(),
    verified_by     = $4,
    updated_at      = NOW()
WHERE id = $1
RETURNING id, fulfillment_id, tracking_number, carrier, proof_photo_url, status, delivered_at, verified_at, verified_by, created_at, updated_at
`

type VerifyDeliveryParams struct {
	ID            uuid.UUID          `json:"id"`
	ProofPhotoUrl *string            `json:"proof_photo_url"`
	DeliveredAt   pgtype.Timestamptz `json:"delivered_at"`
	VerifiedBy    pgtype.UUID        `json:"verified_by"`
}

func (q *Queries) VerifyDelivery(ctx context.Context, arg VerifyDeliveryParams) (Delivery, error) {
	row := q.db.QueryRow(ctx, verifyDelivery,
		arg.ID,
		arg.ProofPhotoUrl,
		arg.DeliveredAt,
		arg.VerifiedBy,
	)
	var i Delivery
	err := row.Scan(
		&i.ID,
		&i.FulfillmentID,
		&i.TrackingNumber,
		&i.Carrier,
		&i.ProofPhotoUrl,
		&i.Status,
		&i.DeliveredAt,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
