// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: fulfillments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countFulfillments = `-- name: CountFulfillments :one
SELECT COUNT(*) FROM fulfillments
`

func (q *Queries) CountFulfillments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFulfillments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFulfillment = `-- name: CreateFulfillment :one
INSERT INTO fulfillments (request_id)
VALUES ($1)
RETURNING id, request_id, vendor_name, vendor_ref, actual_cost, procurement_status, notes, procured_at, created_at, updated_at
`

func (q *Queries) CreateFulfillment(ctx context.Context, requestID uuid.UUID) (Fulfillment, error) {
	row := q.db.QueryRow(ctx, createFulfillment, requestID)
	var i Fulfillment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorName,
		&i.VendorRef,
		&i.ActualCost,
		&i.ProcurementStatus,
		&i.Notes,
		&i.ProcuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFulfillmentByID = `-- name: GetFulfillmentByID :one
SELECT id, request_id, vendor_name, vendor_ref, actual_cost, procurement_status, notes, procured_at, created_at, updated_at FROM fulfillments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFulfillmentByID(ctx context.Context, id uuid.UUID) (Fulfillment, error) {
	row := q.db.QueryRow(ctx, getFulfillmentByID, id)
	var i Fulfillment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorName,
		&i.VendorRef,
		&i.ActualCost,
		&i.ProcurementStatus,
		&i.Notes,
		&i.ProcuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFulfillmentByRequestID = `-- name: GetFulfillmentByRequestID :one
SELECT id, request_id, vendor_name, vendor_ref, actual_cost, procurement_status, notes, procured_at, created_at, updated_at FROM fulfillments WHERE request_id = $1 LIMIT 1
`

func (q *Queries) GetFulfillmentByRequestID(ctx context.Context, requestID uuid.UUID) (Fulfillment, error) {
	row := q.db.QueryRow(ctx, getFulfillmentByRequestID, requestID)
	var i Fulfillment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorName,
		&i.VendorRef,
		&i.ActualCost,
		&i.ProcurementStatus,
		&i.Notes,
		&i.ProcuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFulfillments = `-- name: ListFulfillments :many
SELECT id, request_id, vendor_name, vendor_ref, actual_cost, procurement_status, notes, procured_at, created_at, updated_at FROM fulfillments
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListFulfillmentsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListFulfillments(ctx context.Context, arg ListFulfillmentsParams) ([]Fulfillment, error) {
	rows, err := q.db.Query(ctx, listFulfillments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Fulfillment{}
	for rows.Next() {
		var i Fulfillment
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.VendorName,
			&i.VendorRef,
			&i.ActualCost,
			&i.ProcurementStatus,
			&i.Notes,
			&i.ProcuredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFulfillment = `-- name: UpdateFulfillment :one
UPDATE fulfillments
SET
    vendor_name        = COALESCE($1, vendor_name),
    vendor_ref         = COALESCE($2, vendor_ref),
    actual_cost        = COALESCE($3, actual_cost),
    procurement_status = COALESCE($4, procurement_status),
    notes              = COALESCE($5, notes),
    procured_at        = COALESCE($6, procured_at),
    updated_at         = NOW()
WHERE id = $7
RETURNING id, request_id, vendor_name, vendor_ref, actual_cost, procurement_status, notes, procured_at, created_at, updated_at
`

type UpdateFulfillmentParams struct {
	VendorName        *string               `json:"vendor_name"`
	VendorRef         *string               `json:"vendor_ref"`
	ActualCost        pgtype.Numeric        `json:"actual_cost"`
	ProcurementStatus NullFulfillmentStatus `json:"procurement_status"`
	Notes             *string               `json:"notes"`
	ProcuredAt        pgtype.Timestamptz    `json:"procured_at"`
	ID                uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateFulfillment(ctx context.Context, arg UpdateFulfillmentParams) (Fulfillment, error) {
	row := q.db.QueryRow(ctx, updateFulfillment,
		arg.VendorName,
		arg.VendorRef,
		arg.ActualCost,
		arg.ProcurementStatus,
		arg.Notes,
		arg.ProcuredAt,
		arg.ID,
	)
	var i Fulfillment
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.VendorName,
		&i.VendorRef,
		&i.ActualCost,
		&i.ProcurementStatus,
		&i.Notes,
		&i.ProcuredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
