// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: impact.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countImpactByUser = `-- name: CountImpactByUser :one
SELECT COUNT(*) FROM impact_records WHERE user_id = $1
`

func (q *Queries) CountImpactByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countImpactByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImpactRecord = `-- name: CreateImpactRecord :one
INSERT INTO impact_records
    (delivery_id, user_id, interval_label, outcome_description, satisfaction_score, metrics)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, delivery_id, user_id, interval_label, outcome_description, satisfaction_score, metrics, recorded_at
`

type CreateImpactRecordParams struct {
	DeliveryID         uuid.UUID       `json:"delivery_id"`
	UserID             uuid.UUID       `json:"user_id"`
	IntervalLabel      string          `json:"interval_label"`
	OutcomeDescription *string         `json:"outcome_description"`
	SatisfactionScore  *int16          `json:"satisfaction_score"`
	Metrics            json.RawMessage `json:"metrics"`
}

func (q *Queries) CreateImpactRecord(ctx context.Context, arg CreateImpactRecordParams) (ImpactRecord, error) {
	row := q.db.QueryRow(ctx, createImpactRecord,
		arg.DeliveryID,
		arg.UserID,
		arg.IntervalLabel,
		arg.OutcomeDescription,
		arg.SatisfactionScore,
		arg.Metrics,
	)
	var i ImpactRecord
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.UserID,
		&i.IntervalLabel,
		&i.OutcomeDescription,
		&i.SatisfactionScore,
		&i.Metrics,
		&i.RecordedAt,
	)
	return i, err
}

const getImpactRecordByID = `-- name: GetImpactRecordByID :one
SELECT id, delivery_id, user_id, interval_label, outcome_description, satisfaction_score, metrics, recorded_at FROM impact_records WHERE id = $1 LIMIT 1
`

func (q *Queries) GetImpactRecordByID(ctx context.Context, id uuid.UUID) (ImpactRecord, error) {
	row := q.db.QueryRow(ctx, getImpactRecordByID, id)
	var i ImpactRecord
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.UserID,
		&i.IntervalLabel,
		&i.OutcomeDescription,
		&i.SatisfactionScore,
		&i.Metrics,
		&i.RecordedAt,
	)
	return i, err
}

const listImpactByDelivery = `-- name: ListImpactByDelivery :many
SELECT id, delivery_id, user_id, interval_label, outcome_description, satisfaction_score, metrics, recorded_at FROM impact_records
WHERE delivery_id = $1
ORDER BY recorded_at ASC
`

func (q *Queries) ListImpactByDelivery(ctx context.Context, deliveryID uuid.UUID) ([]ImpactRecord, error) {
	rows, err := q.db.Query(ctx, listImpactByDelivery, deliveryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImpactRecord{}
	for rows.Next() {
		var i ImpactRecord
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.UserID,
			&i.IntervalLabel,
			&i.OutcomeDescription,
			&i.SatisfactionScore,
			&i.Metrics,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImpactByUser = `-- name: ListImpactByUser :many
SELECT id, delivery_id, user_id, interval_label, outcome_description, satisfaction_score, metrics, recorded_at FROM impact_records
WHERE user_id = $1
ORDER BY recorded_at DESC
LIMIT $2 OFFSET $3
`

type ListImpactByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListImpactByUser(ctx context.Context, arg ListImpactByUserParams) ([]ImpactRecord, error) {
	rows, err := q.db.Query(ctx, listImpactByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ImpactRecord{}
	for rows.Next() {
		var i ImpactRecord
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryID,
			&i.UserID,
			&i.IntervalLabel,
			&i.OutcomeDescription,
			&i.SatisfactionScore,
			&i.Metrics,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
