// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: institutions.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countInstitutionalContributions = `-- name: CountInstitutionalContributions :one
SELECT COUNT(*) FROM institutional_contributions WHERE institution_id = $1
`

func (q *Queries) CountInstitutionalContributions(ctx context.Context, institutionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInstitutionalContributions, institutionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInstitution = `-- name: CreateInstitution :one
INSERT INTO institutions (user_id, name, type, contact_email, website, esg_goals)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, name, type, contact_email, website, esg_goals, verified, joined_at, updated_at
`

type CreateInstitutionParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	Name         string          `json:"name"`
	Type         string          `json:"type"`
	ContactEmail string          `json:"contact_email"`
	Website      *string         `json:"website"`
	EsgGoals     json.RawMessage `json:"esg_goals"`
}

func (q *Queries) CreateInstitution(ctx context.Context, arg CreateInstitutionParams) (Institution, error) {
	row := q.db.QueryRow(ctx, createInstitution,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.ContactEmail,
		arg.Website,
		arg.EsgGoals,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ContactEmail,
		&i.Website,
		&i.EsgGoals,
		&i.Verified,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createInstitutionalContribution = `-- name: CreateInstitutionalContribution :one
INSERT INTO institutional_contributions
    (institution_id, pool_id, amount, currency, category_tag, region_tag)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, institution_id, pool_id, amount, currency, status, payment_ref, category_tag, region_tag, notes, created_at, updated_at
`

type CreateInstitutionalContributionParams struct {
	InstitutionID uuid.UUID `json:"institution_id"`
	PoolID        uuid.UUID `json:"pool_id"`
	Amount        float64   `json:"amount"`
	Currency      string    `json:"currency"`
	CategoryTag   *string   `json:"category_tag"`
	RegionTag     *string   `json:"region_tag"`
}

func (q *Queries) CreateInstitutionalContribution(ctx context.Context, arg CreateInstitutionalContributionParams) (InstitutionalContribution, error) {
	row := q.db.QueryRow(ctx, createInstitutionalContribution,
		arg.InstitutionID,
		arg.PoolID,
		arg.Amount,
		arg.Currency,
		arg.CategoryTag,
		arg.RegionTag,
	)
	var i InstitutionalContribution
	err := row.Scan(
		&i.ID,
		&i.InstitutionID,
		&i.PoolID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.PaymentRef,
		&i.CategoryTag,
		&i.RegionTag,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstitutionByID = `-- name: GetInstitutionByID :one
SELECT id, user_id, name, type, contact_email, website, esg_goals, verified, joined_at, updated_at FROM institutions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInstitutionByID(ctx context.Context, id uuid.UUID) (Institution, error) {
	row := q.db.QueryRow(ctx, getInstitutionByID, id)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ContactEmail,
		&i.Website,
		&i.EsgGoals,
		&i.Verified,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstitutionByUserID = `-- name: GetInstitutionByUserID :one
SELECT id, user_id, name, type, contact_email, website, esg_goals, verified, joined_at, updated_at FROM institutions WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetInstitutionByUserID(ctx context.Context, userID uuid.UUID) (Institution, error) {
	row := q.db.QueryRow(ctx, getInstitutionByUserID, userID)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ContactEmail,
		&i.Website,
		&i.EsgGoals,
		&i.Verified,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstitutionalContributions = `-- name: ListInstitutionalContributions :many
SELECT id, institution_id, pool_id, amount, currency, status, payment_ref, category_tag, region_tag, notes, created_at, updated_at FROM institutional_contributions
WHERE institution_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListInstitutionalContributionsParams struct {
	InstitutionID uuid.UUID `json:"institution_id"`
	Limit         int32     `json:"limit"`
	Offset        int32     `json:"offset"`
}

func (q *Queries) ListInstitutionalContributions(ctx context.Context, arg ListInstitutionalContributionsParams) ([]InstitutionalContribution, error) {
	rows, err := q.db.Query(ctx, listInstitutionalContributions, arg.InstitutionID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstitutionalContribution{}
	for rows.Next() {
		var i InstitutionalContribution
		if err := rows.Scan(
			&i.ID,
			&i.InstitutionID,
			&i.PoolID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.PaymentRef,
			&i.CategoryTag,
			&i.RegionTag,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstitution = `-- name: UpdateInstitution :one
UPDATE institutions
SET
    name          = COALESCE($1, name),
    type          = COALESCE($2, type),
    contact_email = COALESCE($3, contact_email),
    website       = COALESCE($4, website),
    esg_goals     = COALESCE($5, esg_goals),
    verified      = COALESCE($6, verified),
    updated_at    = NOW()
WHERE id = $7
RETURNING id, user_id, name, type, contact_email, website, esg_goals, verified, joined_at, updated_at
`

type UpdateInstitutionParams struct {
	Name         *string             `json:"name"`
	Type         NullInstitutionType `json:"type"`
	ContactEmail *string             `json:"contact_email"`
	Website      *string             `json:"website"`
	EsgGoals     []byte              `json:"esg_goals"`
	Verified     *bool               `json:"verified"`
	ID           uuid.UUID           `json:"id"`
}

func (q *Queries) UpdateInstitution(ctx context.Context, arg UpdateInstitutionParams) (Institution, error) {
	row := q.db.QueryRow(ctx, updateInstitution,
		arg.Name,
		arg.Type,
		arg.ContactEmail,
		arg.Website,
		arg.EsgGoals,
		arg.Verified,
		arg.ID,
	)
	var i Institution
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.ContactEmail,
		&i.Website,
		&i.EsgGoals,
		&i.Verified,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return i, err
}
