// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ContributionStatus string

const (
	ContributionStatusPending   ContributionStatus = "pending"
	ContributionStatusCompleted ContributionStatus = "completed"
	ContributionStatusFailed    ContributionStatus = "failed"
	ContributionStatusRefunded  ContributionStatus = "refunded"
)

func (e *ContributionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContributionStatus(s)
	case string:
		*e = ContributionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ContributionStatus: %T", src)
	}
	return nil
}

type NullContributionStatus struct {
	ContributionStatus ContributionStatus `json:"contribution_status"`
	Valid              bool               `json:"valid"` // Valid is true if ContributionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContributionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ContributionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContributionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContributionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContributionStatus), nil
}

type DeliveryStatus string

const (
	DeliveryStatusInTransit DeliveryStatus = "in_transit"
	DeliveryStatusDelivered DeliveryStatus = "delivered"
	DeliveryStatusFailed    DeliveryStatus = "failed"
	DeliveryStatusReturned  DeliveryStatus = "returned"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type FulfillmentStatus string

const (
	FulfillmentStatusPending        FulfillmentStatus = "pending"
	FulfillmentStatusVendorSelected FulfillmentStatus = "vendor_selected"
	FulfillmentStatusOrdered        FulfillmentStatus = "ordered"
	FulfillmentStatusShipped        FulfillmentStatus = "shipped"
	FulfillmentStatusDelivered      FulfillmentStatus = "delivered"
	FulfillmentStatusCancelled      FulfillmentStatus = "cancelled"
)

func (e *FulfillmentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FulfillmentStatus(s)
	case string:
		*e = FulfillmentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FulfillmentStatus: %T", src)
	}
	return nil
}

type NullFulfillmentStatus struct {
	FulfillmentStatus FulfillmentStatus `json:"fulfillment_status"`
	Valid             bool              `json:"valid"` // Valid is true if FulfillmentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFulfillmentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FulfillmentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FulfillmentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFulfillmentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FulfillmentStatus), nil
}

type InstitutionType string

const (
	InstitutionTypeCorporation InstitutionType = "corporation"
	InstitutionTypeNgo         InstitutionType = "ngo"
	InstitutionTypeGovernment  InstitutionType = "government"
	InstitutionTypeFoundation  InstitutionType = "foundation"
	InstitutionTypeOther       InstitutionType = "other"
)

func (e *InstitutionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstitutionType(s)
	case string:
		*e = InstitutionType(s)
	default:
		return fmt.Errorf("unsupported scan type for InstitutionType: %T", src)
	}
	return nil
}

type NullInstitutionType struct {
	InstitutionType InstitutionType `json:"institution_type"`
	Valid           bool            `json:"valid"` // Valid is true if InstitutionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstitutionType) Scan(value interface{}) error {
	if value == nil {
		ns.InstitutionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstitutionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstitutionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstitutionType), nil
}

type RequestStatus string

const (
	RequestStatusDraft     RequestStatus = "draft"
	RequestStatusSubmitted RequestStatus = "submitted"
	RequestStatusVerified  RequestStatus = "verified"
	RequestStatusQueued    RequestStatus = "queued"
	RequestStatusFunded    RequestStatus = "funded"
	RequestStatusProcuring RequestStatus = "procuring"
	RequestStatusDelivered RequestStatus = "delivered"
	RequestStatusCompleted RequestStatus = "completed"
	RequestStatusRejected  RequestStatus = "rejected"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type UrgencyLevel string

const (
	UrgencyLevelCritical UrgencyLevel = "critical"
	UrgencyLevelHigh     UrgencyLevel = "high"
	UrgencyLevelStandard UrgencyLevel = "standard"
	UrgencyLevelLow      UrgencyLevel = "low"
)

func (e *UrgencyLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UrgencyLevel(s)
	case string:
		*e = UrgencyLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for UrgencyLevel: %T", src)
	}
	return nil
}

type NullUrgencyLevel struct {
	UrgencyLevel UrgencyLevel `json:"urgency_level"`
	Valid        bool         `json:"valid"` // Valid is true if UrgencyLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUrgencyLevel) Scan(value interface{}) error {
	if value == nil {
		ns.UrgencyLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UrgencyLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUrgencyLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UrgencyLevel), nil
}

type UserRoles string

const (
	UserRolesMember      UserRoles = "member"
	UserRolesAdmin       UserRoles = "admin"
	UserRolesInstitution UserRoles = "institution"
)

func (e *UserRoles) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRoles(s)
	case string:
		*e = UserRoles(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRoles: %T", src)
	}
	return nil
}

type NullUserRoles struct {
	UserRoles UserRoles `json:"user_roles"`
	Valid     bool      `json:"valid"` // Valid is true if UserRoles is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRoles) Scan(value interface{}) error {
	if value == nil {
		ns.UserRoles, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRoles.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRoles) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRoles), nil
}

type Contribution struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	PoolID     uuid.UUID          `json:"pool_id"`
	Amount     float64            `json:"amount"`
	Currency   string             `json:"currency"`
	Status     string             `json:"status"`
	PaymentRef *string            `json:"payment_ref"`
	StripePiID *string            `json:"stripe_pi_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Delivery struct {
	ID             uuid.UUID          `json:"id"`
	FulfillmentID  uuid.UUID          `json:"fulfillment_id"`
	TrackingNumber *string            `json:"tracking_number"`
	Carrier        *string            `json:"carrier"`
	ProofPhotoUrl  *string            `json:"proof_photo_url"`
	Status         string             `json:"status"`
	DeliveredAt    pgtype.Timestamptz `json:"delivered_at"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
	VerifiedBy     pgtype.UUID        `json:"verified_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Fulfillment struct {
	ID                uuid.UUID          `json:"id"`
	RequestID         uuid.UUID          `json:"request_id"`
	VendorName        *string            `json:"vendor_name"`
	VendorRef         *string            `json:"vendor_ref"`
	ActualCost        pgtype.Numeric     `json:"actual_cost"`
	ProcurementStatus string             `json:"procurement_status"`
	Notes             *string            `json:"notes"`
	ProcuredAt        pgtype.Timestamptz `json:"procured_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type ImpactRecord struct {
	ID                 uuid.UUID          `json:"id"`
	DeliveryID         uuid.UUID          `json:"delivery_id"`
	UserID             uuid.UUID          `json:"user_id"`
	IntervalLabel      string             `json:"interval_label"`
	OutcomeDescription *string            `json:"outcome_description"`
	SatisfactionScore  *int16             `json:"satisfaction_score"`
	Metrics            json.RawMessage    `json:"metrics"`
	RecordedAt         pgtype.Timestamptz `json:"recorded_at"`
}

type Institution struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	Name         string             `json:"name"`
	Type         string             `json:"type"`
	ContactEmail string             `json:"contact_email"`
	Website      *string            `json:"website"`
	EsgGoals     json.RawMessage    `json:"esg_goals"`
	Verified     bool               `json:"verified"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionalContribution struct {
	ID            uuid.UUID          `json:"id"`
	InstitutionID uuid.UUID          `json:"institution_id"`
	PoolID        uuid.UUID          `json:"pool_id"`
	Amount        float64            `json:"amount"`
	Currency      string             `json:"currency"`
	Status        string             `json:"status"`
	PaymentRef    *string            `json:"payment_ref"`
	CategoryTag   *string            `json:"category_tag"`
	RegionTag     *string            `json:"region_tag"`
	Notes         *string            `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Pool struct {
	ID        uuid.UUID          `json:"id"`
	Balance   float64            `json:"balance"`
	TotalIn   float64            `json:"total_in"`
	TotalOut  float64            `json:"total_out"`
	Currency  string             `json:"currency"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type QueueEntry struct {
	ID                   uuid.UUID          `json:"id"`
	RequestID            uuid.UUID          `json:"request_id"`
	Position             int32              `json:"position"`
	FundingProgress      float64            `json:"funding_progress"`
	EstimatedFulfillment pgtype.Date        `json:"estimated_fulfillment"`
	EnteredAt            pgtype.Timestamptz `json:"entered_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Request struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	ItemCategory  string             `json:"item_category"`
	ItemName      string             `json:"item_name"`
	Description   string             `json:"description"`
	Urgency       string             `json:"urgency"`
	EstimatedCost float64            `json:"estimated_cost"`
	Justification string             `json:"justification"`
	Status        string             `json:"status"`
	RejectionNote *string            `json:"rejection_note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	Role         UserRoles          `json:"role"`
	PasswordHash string             `json:"password_hash"`
	Verified     bool               `json:"verified"`
	JoinedAt     pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
