// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pools.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const creditPool = `-- name: CreditPool :exec
UPDATE pools
SET
    balance    = balance + $1,
    total_in   = total_in + $1,
    updated_at = NOW()
WHERE id = $2
`

type CreditPoolParams struct {
	Amount float64   `json:"amount"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) CreditPool(ctx context.Context, arg CreditPoolParams) error {
	_, err := q.db.Exec(ctx, creditPool, arg.Amount, arg.ID)
	return err
}

const debitPool = `-- name: DebitPool :execrows
UPDATE pools
SET
    balance    = balance - $1,
    total_out  = total_out + $1,
    updated_at = NOW()
WHERE id = $2 AND balance >= $1
`

type DebitPoolParams struct {
	Amount float64   `json:"amount"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) DebitPool(ctx context.Context, arg DebitPoolParams) (int64, error) {
	result, err := q.db.Exec(ctx, debitPool, arg.Amount, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPool = `-- name: GetPool :one
SELECT id, balance, total_in, total_out, currency, updated_at FROM pools WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPool(ctx context.Context, id uuid.UUID) (Pool, error) {
	row := q.db.QueryRow(ctx, getPool, id)
	var i Pool
	err := row.Scan(
		&i.ID,
		&i.Balance,
		&i.TotalIn,
		&i.TotalOut,
		&i.Currency,
		&i.UpdatedAt,
	)
	return i, err
}
