// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queue.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countQueueEntries = `-- name: CountQueueEntries :one
SELECT COUNT(*) FROM queue_entries
`

func (q *Queries) CountQueueEntries(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countQueueEntries)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dequeueRequest = `-- name: DequeueRequest :exec
DELETE FROM queue_entries WHERE request_id = $1
`

func (q *Queries) DequeueRequest(ctx context.Context, requestID uuid.UUID) error {
	_, err := q.db.Exec(ctx, dequeueRequest, requestID)
	return err
}

const enqueueRequest = `-- name: EnqueueRequest :one
INSERT INTO queue_entries (request_id, position)
VALUES ($1, $2)
RETURNING id, request_id, position, funding_progress, estimated_fulfillment, entered_at, updated_at
`

type EnqueueRequestParams struct {
	RequestID uuid.UUID `json:"request_id"`
	Position  int32     `json:"position"`
}

func (q *Queries) EnqueueRequest(ctx context.Context, arg EnqueueRequestParams) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, enqueueRequest, arg.RequestID, arg.Position)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Position,
		&i.FundingProgress,
		&i.EstimatedFulfillment,
		&i.EnteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueueEntryByRequestID = `-- name: GetQueueEntryByRequestID :one
SELECT id, request_id, position, funding_progress, estimated_fulfillment, entered_at, updated_at FROM queue_entries WHERE request_id = $1 LIMIT 1
`

func (q *Queries) GetQueueEntryByRequestID(ctx context.Context, requestID uuid.UUID) (QueueEntry, error) {
	row := q.db.QueryRow(ctx, getQueueEntryByRequestID, requestID)
	var i QueueEntry
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.Position,
		&i.FundingProgress,
		&i.EstimatedFulfillment,
		&i.EnteredAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQueuePosition = `-- name: GetQueuePosition :one
SELECT position FROM queue_entries WHERE request_id = $1 LIMIT 1
`

func (q *Queries) GetQueuePosition(ctx context.Context, requestID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getQueuePosition, requestID)
	var position int32
	err := row.Scan(&position)
	return position, err
}

const listAllQueueEntries = `-- name: ListAllQueueEntries :many
SELECT id, request_id, position, funding_progress, estimated_fulfillment, entered_at, updated_at FROM queue_entries
ORDER BY entered_at ASC
`

func (q *Queries) ListAllQueueEntries(ctx context.Context) ([]QueueEntry, error) {
	rows, err := q.db.Query(ctx, listAllQueueEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueEntry{}
	for rows.Next() {
		var i QueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Position,
			&i.FundingProgress,
			&i.EstimatedFulfillment,
			&i.EnteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueueEntries = `-- name: ListQueueEntries :many
SELECT id, request_id, position, funding_progress, estimated_fulfillment, entered_at, updated_at FROM queue_entries
ORDER BY entered_at ASC
LIMIT $1 OFFSET $2
`

type ListQueueEntriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListQueueEntries(ctx context.Context, arg ListQueueEntriesParams) ([]QueueEntry, error) {
	rows, err := q.db.Query(ctx, listQueueEntries, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QueueEntry{}
	for rows.Next() {
		var i QueueEntry
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.Position,
			&i.FundingProgress,
			&i.EstimatedFulfillment,
			&i.EnteredAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxQueuePosition = `-- name: MaxQueuePosition :one
SELECT COALESCE(MAX(position), 0)::int4 AS max_position FROM queue_entries
`

func (q *Queries) MaxQueuePosition(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, maxQueuePosition)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const updateQueueFunding = `-- name: UpdateQueueFunding :exec
UPDATE queue_entries
SET funding_progress = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateQueueFundingParams struct {
	ID              uuid.UUID `json:"id"`
	FundingProgress float64   `json:"funding_progress"`
}

func (q *Queries) UpdateQueueFunding(ctx context.Context, arg UpdateQueueFundingParams) error {
	_, err := q.db.Exec(ctx, updateQueueFunding, arg.ID, arg.FundingProgress)
	return err
}

const updateQueuePosition = `-- name: UpdateQueuePosition :exec
UPDATE queue_entries
SET position = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateQueuePositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateQueuePosition(ctx context.Context, arg UpdateQueuePositionParams) error {
	_, err := q.db.Exec(ctx, updateQueuePosition, arg.ID, arg.Position)
	return err
}
