// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countAllRequests = `-- name: CountAllRequests :one
SELECT COUNT(*) FROM requests
`

func (q *Queries) CountAllRequests(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAllRequests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByStatus = `-- name: CountRequestsByStatus :one
SELECT COUNT(*) FROM requests WHERE status = $1
`

func (q *Queries) CountRequestsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRequestsByUser = `-- name: CountRequestsByUser :one
SELECT COUNT(*) FROM requests WHERE user_id = $1
`

func (q *Queries) CountRequestsByUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRequestsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRequest = `-- name: CreateRequest :one
INSERT INTO requests (user_id, item_category, item_name, description, urgency, estimated_cost, justification, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at
`

type CreateRequestParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ItemCategory  string    `json:"item_category"`
	ItemName      string    `json:"item_name"`
	Description   string    `json:"description"`
	Urgency       string    `json:"urgency"`
	EstimatedCost float64   `json:"estimated_cost"`
	Justification string    `json:"justification"`
	Status        string    `json:"status"`
}

func (q *Queries) CreateRequest(ctx context.Context, arg CreateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, createRequest,
		arg.UserID,
		arg.ItemCategory,
		arg.ItemName,
		arg.Description,
		arg.Urgency,
		arg.EstimatedCost,
		arg.Justification,
		arg.Status,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemCategory,
		&i.ItemName,
		&i.Description,
		&i.Urgency,
		&i.EstimatedCost,
		&i.Justification,
		&i.Status,
		&i.RejectionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDraftRequest = `-- name: DeleteDraftRequest :execrows
DELETE FROM requests WHERE id = $1 AND status = 'draft'
`

func (q *Queries) DeleteDraftRequest(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDraftRequest, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRequestByID = `-- name: GetRequestByID :one
SELECT id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at FROM requests WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRequestByID(ctx context.Context, id uuid.UUID) (Request, error) {
	row := q.db.QueryRow(ctx, getRequestByID, id)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemCategory,
		&i.ItemName,
		&i.Description,
		&i.Urgency,
		&i.EstimatedCost,
		&i.Justification,
		&i.Status,
		&i.RejectionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRequests = `-- name: ListAllRequests :many
SELECT id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at FROM requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAllRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAllRequests(ctx context.Context, arg ListAllRequestsParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listAllRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemCategory,
			&i.ItemName,
			&i.Description,
			&i.Urgency,
			&i.EstimatedCost,
			&i.Justification,
			&i.Status,
			&i.RejectionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByStatus = `-- name: ListRequestsByStatus :many
SELECT id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at FROM requests
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRequestsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListRequestsByStatus(ctx context.Context, arg ListRequestsByStatusParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemCategory,
			&i.ItemName,
			&i.Description,
			&i.Urgency,
			&i.EstimatedCost,
			&i.Justification,
			&i.Status,
			&i.RejectionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsByUser = `-- name: ListRequestsByUser :many
SELECT id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at FROM requests
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRequestsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListRequestsByUser(ctx context.Context, arg ListRequestsByUserParams) ([]Request, error) {
	rows, err := q.db.Query(ctx, listRequestsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Request{}
	for rows.Next() {
		var i Request
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemCategory,
			&i.ItemName,
			&i.Description,
			&i.Urgency,
			&i.EstimatedCost,
			&i.Justification,
			&i.Status,
			&i.RejectionNote,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRequest = `-- name: UpdateRequest :one
UPDATE requests
SET
    item_category  = COALESCE($1, item_category),
    item_name      = COALESCE($2, item_name),
    description    = COALESCE($3, description),
    urgency        = COALESCE($4, urgency),
    estimated_cost = COALESCE($5, estimated_cost),
    justification  = COALESCE($6, justification),
    updated_at     = NOW()
WHERE id = $7 AND status IN ('draft', 'submitted')
RETURNING id, user_id, item_category, item_name, description, urgency, estimated_cost, justification, status, rejection_note, created_at, updated_at
`

type UpdateRequestParams struct {
	ItemCategory  *string          `json:"item_category"`
	ItemName      *string          `json:"item_name"`
	Description   *string          `json:"description"`
	Urgency       NullUrgencyLevel `json:"urgency"`
	EstimatedCost *float64         `json:"estimated_cost"`
	Justification *string          `json:"justification"`
	ID            uuid.UUID        `json:"id"`
}

func (q *Queries) UpdateRequest(ctx context.Context, arg UpdateRequestParams) (Request, error) {
	row := q.db.QueryRow(ctx, updateRequest,
		arg.ItemCategory,
		arg.ItemName,
		arg.Description,
		arg.Urgency,
		arg.EstimatedCost,
		arg.Justification,
		arg.ID,
	)
	var i Request
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemCategory,
		&i.ItemName,
		&i.Description,
		&i.Urgency,
		&i.EstimatedCost,
		&i.Justification,
		&i.Status,
		&i.RejectionNote,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRequestStatus = `-- name: UpdateRequestStatus :exec
UPDATE requests
SET status = $2, rejection_note = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateRequestStatusParams struct {
	ID            uuid.UUID `json:"id"`
	Status        string    `json:"status"`
	RejectionNote *string   `json:"rejection_note"`
}

func (q *Queries) UpdateRequestStatus(ctx context.Context, arg UpdateRequestStatusParams) error {
	_, err := q.db.Exec(ctx, updateRequestStatus, arg.ID, arg.Status, arg.RejectionNote)
	return err
}
